let shopItemsData = [
  {
    id: "jfhgbvnscs1",
    name: "Kutusha With Senselet",
    price: 58,
    desc: "Kutusha With Senselet",
    img: "images/acc5.png",
  },
  {
    id: "ioytrhndcv2",
    name: "Kutusha With Senselet",
    price: 75,
    desc: "Kutusha With Senselet",
    img: "images/acc6.png",
  },
  {
    id: "wuefbncxbsn3",
    name: "Kutusha With Senselet",
    price: 85,
    desc: "Kutusha With Senselet",
    img:  "images/acc7.png",
  },
  {
    id: "thyfhcbcv4",
    name: "Kutusha With Senselet",
    price: 58,
    desc: "Kutusha With Senselet",
    img: "images/acc8.png",
  },
  {
    id: "jfhgbvnscs5",
    name: "Kutusha With Senselet",
    price: 59,
    desc: "Kutusha With Senselet",
    img: "images/acc9.png",
  },
  {
    id: "ioytrhndcv6",
    name: "Kutusha With Senselet",
    price: 35,
    desc: "Kutusha With Senselet",
    img: "images/acc10.png",
  },
  {
    id: "wuefbncxbsn7",
    name: "Kutusha With Senselet",
    price: 68,
    desc: "Kutusha With Senselet",
    img: "images/acc11.png",
  },
  {
    id: "thyfhcbcv8",
    name: "Kutusha With Senselet",
    price: 58,
    desc: "Kutusha With Senselet",
    img: "images/habil.png",
  },

  {
    id: "jfhgbvnslmcs9",
    name: "Kutusha With Senselet",
    price: 48,
    desc: "Kutusha With Senselet",
    img: "images/jewel.jpg",
  },
  {
    id: "ioytrhndcv10",
    name: "Kutusha With Senselet",
    price: 98,
    desc: "Kutusha With Senselet",
    img: "images/jewel8.png",
  },
  {
    id: "wuefbncxbsn11a",
    name: "Kutusha With Senselet",
    price: 58,
    desc: "Kutusha With Senselet",
    img: "images/jewel9.png",
  },
  {
    id: "thyfhcbcv12",
    name: "Kutusha With Senselet",
    price: 98,
    desc: "Kutusha With Senselet",
    img: "images/jewel10.png",
  },
  {
    id: "thyfhcbcv13",
    name: "Kutusha With Senselet",
    price: 98,
    desc: "Kutusha With Senselet",
    img: "images/jewel11.png",
  },
];
