let shopItemsData = [
  {
    id: "jfhgbvnscs1",
    name: "Men Top",
    price: 58,
    desc: "Traditional Habesha Top",
    img: "images/men1.png",
  },
  {
    id: "ioytrhndcv2",
    name: "Men Top",
    price: 75,
    desc: "Traditional Habasha Top",
    img: "images/men2.png",
  },
  {
    id: "wuefbncxbsn3",
    name: "Men Top",
    price: 85,
    desc: "Habesha Traditional Top",
    img:  "images/men3.png",
  },
  {
    id: "thyfhcbcv4",
    name: "Eje Tebab",
    price: 58,
    desc: "Traditional Habesha Outfit",
    img: "images/men4.png",
  },
  {
    id: "jfhgbvnscs5",
    name: "Men Top",
    price: 59,
    desc: "Traditional Habesha Top",
    img: "images/men5.png",
  },
  {
    id: "ioytrhndcv6",
    name: "Men Top",
    price: 35,
    desc: "Traditional Habesha Top",
    img: "images/men6.png",
  },
  {
    id: "wuefbncxbsn7",
    name: "Men Top",
    price: 68,
    desc: "Traditional Habesha Top",
    img: "images/men7.png",
  },
  {
    id: "thyfhcbcv8",
    name: "Men Top",
    price: 58,
    desc: "Traditional Habesha Top",
    img: "images/men8.png",
  },

  {
    id: "jfhgbvnscs9",
    name: "Men Top",
    price: 48,
    desc: "Summer Habesha Top",
    img: "images/men9.png",
  },
  {
    id: "ioytrhndcv10",
    name: "Men Top",
    price: 98,
    desc: "Traditional Habesha Top",
    img: "images/men10.png",
  },
  {
    id: "wuefbncxbsn11",
    name: "Men Top",
    price: 58,
    desc: "Traditional Habesha Top",
    img: "images/men11.png",
  },
  {
    id: "thyfhcbcv12",
    name: "Men Top",
    price: 98,
    desc: "Traditional Habesha Top",
    img: "images/men12.png",
  },
  {
    id: "thyfhcbcv13",
    name: "Men Top",
    price: 98,
    desc: "Traditional Habesha Top",
    img: "images/men_special.png",
  },
  {
    id: "thyfhcbcv13",
    name: "Wedding Apparel",
    price: 98,
    desc: "Traditional Habesha Apparel",
    img: "images/wed2.png",
  },
];
