let shopItemsData = [
  {
    id: "jfhgbvnscs1",
    name: "Dinner Dress",
    price: 58,
    desc: "Traditional Habesha Dress",
    img: "images/dress1.png",
  },
  {
    id: "ioytrhndcv2",
    name: "Knee-Cut Dress",
    price: 75,
    desc: "Traditional Habasha Dress",
    img: "images/kneesize.jpg",
  },
  {
    id: "wuefbncxbsn3",
    name: "Long Dress",
    price: 85,
    desc: "Habesha Traditional Dress",
    img:  "images/dress2.png",
  },
  {
    id: "thyfhcbcv4",
    name: "Zuriya Dress",
    price: 58,
    desc: "Traditional Habesha Dress",
    img: "images/dress3.png",
  },
  {
    id: "jfhgbvnscs5",
    name: "Tilfi Dress",
    price: 59,
    desc: "Traditional Habesha Dress",
    img: "images/dress4.png",
  },
  {
    id: "ioytrhndcv6",
    name: "Casual Dress",
    price: 35,
    desc: "Traditional Habesha Dress",
    img: "images/dress5.png",
  },
  {
    id: "wuefbncxbsn7",
    name: "Tilfi Dress",
    price: 68,
    desc: "Traditional Habesha Dress",
    img: "images/dress6.png",
  },
  {
    id: "thyfhcbcv8",
    name: "Zuriya Dress",
    price: 58,
    desc: "Traditional Habesha Dress",
    img: "images/dress7.png",
  },
  //
  {
    id: "jfhgbvnscs1",
    name: "Netsela",
    price: 58,
    desc: "Traditional Habesha Dress",
    img: "images/acc1.png",
  },
  {
    id: "ioytrhndcv2",
    name: "Kaba",
    price: 75,
    desc: "Traditional Habasha Dress",
    img: "images/acc2.png",
  },
  {
    id: "wuefbncxbsn3",
    name: "Netsela",
    price: 85,
    desc: "Habesha Traditional Kuta",
    img:  "images/acc3.png",
  },
  {
    id: "thyfhcbcv4",
    name: "Shale",
    price: 58,
    desc: "Netsela",
    img: "images/acc4.png",
  },
  {
    id: "jfhgbvnscs5",
    name: "Jewel",
    price: 59,
    desc: "Traditional Habesha Jewel",
    img: "images/acc5.png",
  },
  {
    id: "ioytrhndcv6",
    name: "Jewel",
    price: 35,
    desc: "Traditional Habesha Jewel",
    img: "images/acc6.png",
  },
  {
    id: "wuefbncxbsn7",
    name: "Jewel",
    price: 68,
    desc: "Traditional Habesha Jewel",
    img: "images/acc7.png",
  },
  {
    id: "thyfhcbcv8",
    name: "Jewel",
    price: 58,
    desc: "Traditional Habesha Jewel",
    img: "images/acc9.png",
  },

  {
    id: "jfhgbvnscs91",
    name: "kaba",
    price: 48,
    desc: "Summer Habesha kaba",
    img: "images/kaba.png",
  },
  {
    id: "ioytrhndcv102",
    name: "kaba",
    price: 98,
    desc: "Traditional Habesha kaba",
    img: "images/tifanny_1.png",
  },
  {
    id: "jfhgbvnscs93",
    name: "Short Dress",
    price: 48,
    desc: "Summer Habesha Dress",
    img: "images/dress8.png",
  },
  {
    id: "ioytrhndcv104",
    name: "Tilfi Dress",
    price: 98,
    desc: "Traditional Habesha Dress",
    img: "images/dress9.png",
  },
  {
    id: "wuefbncxbsn115",
    name: "Women Top",
    price: 58,
    desc: "Traditional Habesha Casual Top",
    img: "images/top1.png",
  },
  {
    id: "thyfhcbcv126",
    name: "Wedding Dress",
    price: 98,
    desc: "Traditional Habesha Wedding Gown",
    img: "images/wed1.png",
  },
  {
    id: "thyfhcbcv137",
    name: "Wedding Dress",
    price: 98,
    desc: "Traditional Habesha Wedding Gown",
    img: "images/wed2.png",
  },
];
