let shopItemsData = [
  {
    id: "jfhgbvnscs1",
    name: "Dinner Dress",
    price: 58,
    desc: "Traditional Habesha Dress",
    img: "images/dress1.png",
  },
  {
    id: "ioytrhndcv2",
    name: "Knee-Cut Dress",
    price: 75,
    desc: "Traditional Habasha Dress",
    img: "images/kneesize.jpg",
  },
  {
    id: "wuefbncxbsn3",
    name: "Long Dress",
    price: 85,
    desc: "Habesha Traditional Dress",
    img:  "images/dress2.png",
  },
  {
    id: "thyfhcbcv4",
    name: "Zuriya Dress",
    price: 58,
    desc: "Traditional Habesha Dress",
    img: "images/dress3.png",
  },
  {
    id: "jfhgbvnscs5",
    name: "Tilfi Dress",
    price: 59,
    desc: "Traditional Habesha Dress",
    img: "images/dress4.png",
  },
  {
    id: "ioytrhndcv6",
    name: "Casual Dress",
    price: 35,
    desc: "Traditional Habesha Dress",
    img: "images/dress5.png",
  },
  {
    id: "wuefbncxbsn7",
    name: "Tilfi Dress",
    price: 68,
    desc: "Traditional Habesha Dress",
    img: "images/dress6.png",
  },
  {
    id: "thyfhcbcv8",
    name: "Zuriya Dress",
    price: 58,
    desc: "Traditional Habesha Dress",
    img: "images/dress7.png",
  },

  {
    id: "jfhgbvnscs9",
    name: "Short Dress",
    price: 48,
    desc: "Summer Habesha Dress",
    img: "images/dress8.png",
  },
  {
    id: "ioytrhndcv10",
    name: "Tilfi Dress",
    price: 98,
    desc: "Traditional Habesha Dress",
    img: "images/dress9.png",
  },
  {
    id: "wuefbncxbsn11",
    name: "Women Top",
    price: 58,
    desc: "Traditional Habesha Casual Top",
    img: "images/top1.png",
  },
  {
    id: "thyfhcbcv12",
    name: "Wedding Dress",
    price: 98,
    desc: "Traditional Habesha Wedding Gown",
    img: "images/wed1.png",
  },
  {
    id: "thyfhcbcv13",
    name: "Wedding Dress",
    price: 98,
    desc: "Traditional Habesha Wedding Gown",
    img: "images/wed2.png",
  },
];
